const FEEDS = [
  {name:"BBC Persian",category:"iran",url:"https://feeds.bbci.co.uk/persian/rss.xml"},
  {name:"Iran International",category:"iran",url:"https://news.google.com/rss/search?q=site%3Airanintl.com+when%3A1h&hl=en-US&gl=US&ceid=US%3Aen"},
  {name:"Radio Farda",category:"iran",url:"https://www.radiofarda.com/api/z-pqpiev-qpp"},
  {name:"DW Farsi",category:"iran",url:"https://rss.dw.com/xml/rss-fa-all"},
  {name:"ISNA",category:"iran",url:"https://www.isna.ir/rss"},
  {name:"Tasnim",category:"iran",url:"https://www.tasnimnews.com/fa/rss/feed/0/8/0/%D9%85%D9%87%D9%85%D8%AA%D8%B1%DB%8C%D9%86-%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1-%D8%AA%D8%B3%D9%86%DB%8C%D9%85"},
  {name:"Tabnak",category:"iran",url:"https://www.tabnak.ir/fa/rss/allnews"},
  {name:"Mehr",category:"iran",url:"https://www.mehrnews.com/rss"},
  {name:"Khabar Online",category:"iran",url:"https://www.khabaronline.ir/rss"},
  {name:"YJC",category:"iran",url:"https://www.yjc.ir/fa/rss/allnews"},
  {name:"Asriran",category:"iran",url:"https://www.asriran.com/fa/rss/allnews"},
  {name:"Fars",category:"iran",url:"https://news.google.com/rss/search?q=site%3Afarsnews.ir+when%3A1h&hl=en-US&gl=US&ceid=US%3Aen"},
  {name:"IRNA",category:"iran",url:"https://en.irna.ir/rss"},
  {name:"ILNA",category:"iran",url:"https://news.google.com/rss/search?q=site%3Ailna.ir+when%3A1h&hl=en-US&gl=US&ceid=US%3Aen"},
  {name:"France 24",category:"iran",url:"https://www.france24.com/en/rss"},
  {name:"Al Jazeera",category:"middle_east",url:"https://www.aljazeera.com/xml/rss/all.xml"},
  {name:"BBC Middle East",category:"middle_east",url:"https://feeds.bbci.co.uk/news/world/middle_east/rss.xml"},
  {name:"The Guardian",category:"middle_east",url:"https://www.theguardian.com/world/middleeast/rss"},
  {name:"The New York Times",category:"middle_east",url:"https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml"},
  {name:"CNN",category:"middle_east",url:"http://rss.cnn.com/rss/edition_meast.rss"},
  {name:"Fox News",category:"middle_east",url:"https://moxie.foxnews.com/google-publisher/world.xml"},
  {name:"Forbes",category:"middle_east",url:"https://www.forbes.com/real-time/feed2/"},
  {name:"The Washington Post",category:"middle_east",url:"https://feeds.washingtonpost.com/rss/world"},
  {name:"The National",category:"middle_east",url:"https://www.thenationalnews.com/rss"},
  {name:"France 24",category:"middle_east",url:"https://www.france24.com/en/rss"},
  {name:"DW",category:"middle_east",url:"https://rss.dw.com/xml/rss-en-all"},
  {name:"Euronews",category:"middle_east",url:"https://www.euronews.com/rss"},
  {name:"BBC World",category:"world",url:"https://feeds.bbci.co.uk/news/world/rss.xml"},
  {name:"The Guardian",category:"world",url:"https://www.theguardian.com/world/rss"},
  {name:"The New York Times",category:"world",url:"https://rss.nytimes.com/services/xml/rss/nyt/World.xml"},
  {name:"CNN",category:"world",url:"http://rss.cnn.com/rss/edition.rss"},
  {name:"Fox News",category:"world",url:"https://moxie.foxnews.com/google-publisher/latest.xml"},
  {name:"The Washington Post",category:"world",url:"https://feeds.washingtonpost.com/rss/world"},
  {name:"DW",category:"world",url:"https://rss.dw.com/xml/rss-en-all"},
  {name:"France 24",category:"world",url:"https://www.france24.com/en/rss"},
  {name:"Euronews",category:"world",url:"https://www.euronews.com/rss"},
  {name:"TASS",category:"world",url:"https://tass.com/rss/v2.xml"},
  {name:"RIA Novosti",category:"world",url:"https://ria.ru/export/rss2/archive/index.xml"},
  {name:"Sputnik",category:"world",url:"https://sputnikglobe.com/export/rss2/archive/index.xml"},
  {name:"RT",category:"world",url:"https://www.rt.com/rss/"},
  {name:"ANSA",category:"world",url:"https://www.ansa.it/sito/ansait_rss.xml"},
  {name:"Politico Europe",category:"world",url:"https://www.politico.eu/feed/"},
  {name:"Al Jazeera",category:"world",url:"https://www.aljazeera.com/xml/rss/all.xml"}
];
const ADMIN_USER_ID="8885912152", ADMIN_USERNAME="clearviolet";
const MIN_AGE=2*60*1000, MAX_AGE=5*60*1000;
export default {async fetch(request,env){try{const u=new URL(request.url);if(request.method==="POST"&&u.pathname==="/telegram")return await handleTelegram(request,env);if(request.method==="GET")return new Response("Nabz is running.");return new Response("Method Not Allowed",{status:405})}catch(e){console.error("FETCH_ERROR",e?.stack||e);return new Response("Internal error",{status:500})}},async scheduled(e,env,ctx){ctx.waitUntil(run(env))}};
async function run(env){await initStats(env);await put(env,"stats:last_run",new Date().toISOString());const r=await Promise.allSettled(FEEDS.map(fetchFeed));let items=[];let ok=0,bad=0;r.forEach((x,i)=>{if(x.status==="fulfilled"){ok++;items.push(...x.value);console.log("RSS_OK",FEEDS[i].name,x.value.length)}else{bad++;console.error("RSS_ERROR",FEEDS[i].name,x.reason?.message||String(x.reason))}});await put(env,"stats:last_feed_success",ok);await put(env,"stats:last_feed_failed",bad);items.sort((a,b)=>new Date(a.publishedAt)-new Date(b.publishedAt));let n=0;for(const item of items){if(n>=Number(env.MAX_PUBLISH_PER_RUN||20))break;const key=`seen:${await sha(`${item.link}|${item.title}`)}`;if(await env.SEEN.get(key))continue;await env.SEEN.put(key,"1",{expirationTtl:172800});try{const tr=await translate(item,env);const tg=await send(item,tr,env);if(!tg?.ok)throw Error(tg?.description||"Telegram error");const now=new Date(),lat=Math.max(0,Math.round((now-new Date(item.publishedAt))/1000));await inc(env,"stats:total");await inc(env,`stats:${item.category}`);await inc(env,`stats:source:${safe(item.feedName)}`);await put(env,"stats:last_published_at",now.toISOString());await put(env,"stats:last_latency_seconds",lat);n++;console.log("PUBLISHED",item.feedName,item.title,lat)}catch(e){console.error("ITEM_ERROR",item.feedName,e?.message||e);await env.SEEN.delete(key)}}console.log("NABZ_CRON_END",n)}
async function fetchFeed(feed){const r=await fetch(feed.url,{headers:{"User-Agent":"Nabz-News-Bot/2.0"}});if(!r.ok)throw Error(`HTTP ${r.status}`);const xml=await r.text(),out=[];for(const b of (xml.match(/<item\b[\s\S]*?<\/item>/gi)||[])){const title=text(xmlv(b,"title")),link=url(xmlv(b,"link")),desc=text(xmlv(b,"description")||xmlv(b,"summary")),d=xmlv(b,"pubDate")||xmlv(b,"published")||xmlv(b,"updated")||xmlv(b,"dc:date");const dt=new Date(d);if(title&&link&&!isNaN(dt)){const age=Date.now()-dt.getTime();if(age>=MIN_AGE&&age<=MAX_AGE)out.push({title,link,description:desc,publishedAt:dt.toISOString(),feedName:feed.name,category:feed.category})}}for(const b of (xml.match(/<entry\b[\s\S]*?<\/entry>/gi)||[])){const title=text(xmlv(b,"title")),desc=text(xmlv(b,"summary")||xmlv(b,"content")),d=xmlv(b,"published")||xmlv(b,"updated"),m=b.match(/<link\b[^>]*href=["']([^"']+)["']/i),link=m?dec(m[1]):url(xmlv(b,"link")),dt=new Date(d);if(title&&link&&!isNaN(dt)){const age=Date.now()-dt.getTime();if(age>=MIN_AGE&&age<=MAX_AGE)out.push({title,link,description:desc,publishedAt:dt.toISOString(),feedName:feed.name,category:feed.category})}}return out}
function xmlv(b,t){const m=b.match(new RegExp(`<${t}\\b[^>]*>([\\s\\S]*?)<\\/${t}>`,"i"));return m?m[1]:""}function text(v){return dec(String(v||"").replace(/<!\[CDATA\[([\s\S]*?)\]\]>/gi,"$1").replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<style[\s\S]*?<\/style>/gi,"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim())}function url(v){return dec(String(v||"").replace(/<!\[CDATA\[([\s\S]*?)\]\]>/gi,"$1").trim())}function dec(v){return String(v).replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/gi,"'")}
async function translate(item,env){const model=env.GEMINI_MODEL||"gemini-3.8-flash";const ep=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`;const prompt=`Translate this news item into natural Persian. Do NOT summarize, add, remove or invent information. Preserve names, organizations, places, numbers and dates. Translate title and supplied description only. Return ONLY JSON: {"title":"...","description":"..."}\nTITLE:\n${item.title}\nDESCRIPTION:\n${item.description||""}`;const r=await fetch(ep,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.1,responseMimeType:"application/json"}})});if(!r.ok)throw Error(`Gemini HTTP ${r.status}`);const d=await r.json(),t=d?.candidates?.[0]?.content?.parts?.map(x=>x.text||"").join("").trim();if(!t)throw Error("Empty Gemini response");try{return JSON.parse(t)}catch{const m=t.match(/\{[\s\S]*\}/);if(!m)throw Error("Invalid Gemini JSON");return JSON.parse(m[0])}}
async function send(item,tr,env){const tag={iran:"#Iran",middle_east:"#Middle_East",world:"#World"}[item.category];const body=[`<b>${eh(tr.title)}</b>`,tr.description?eh(tr.description):"","",`🌐 منبع: ${eh(item.feedName)}`,`🔗 <a href="${ea(item.link)}">مشاهده گزارش اصلی</a>`,tag,"","@Zarathushtra_ir"].filter(Boolean).join("\n");const p={chat_id:norm(env.GROUP_CHAT_ID),text:body,parse_mode:"HTML",disable_web_page_preview:false};const th={iran:env.TOPIC_IRAN,middle_east:env.TOPIC_MIDDLE_EAST,world:env.TOPIC_WORLD}[item.category];if(th)p.message_thread_id=Number(th);return tg(env.BOT_TOKEN,"sendMessage",p)}
async function handleTelegram(req,env){let u;try{u=await req.json()}catch{return new Response("Bad JSON",{status:400})}try{const m=u?.message;if(!m)return new Response("OK");const t=String(m.text||"").trim();if(!t.toLowerCase().startsWith("/start"))return new Response("OK");if(String(m.from?.id||"")!==ADMIN_USER_ID){await tg(env.BOT_TOKEN,"sendMessage",{chat_id:m.chat.id,text:"سلام 👋\n\nبه نبض خوش آمدید.\nاین ربات برای دریافت و انتشار اخبار تازه طراحی شده است."});return new Response("OK")}const s=await stats(env);await tg(env.BOT_TOKEN,"sendMessage",{chat_id:m.chat.id,text:statsText(s),parse_mode:"HTML",disable_web_page_preview:true});return new Response("OK")}catch(e){console.error("TELEGRAM_WEBHOOK_ERROR",e?.message||e);return new Response("OK")}}
async function initStats(env){if(!(await env.SEEN.get("stats:started_at")))await put(env,"stats:started_at",new Date().toISOString())}async function put(env,k,v){await env.SEEN.put(k,String(v),{expirationTtl:315360000})}async function inc(env,k){await put(env,k,Number(await env.SEEN.get(k)||0)+1)}async function stats(env){const a=await Promise.all(["total","iran","middle_east","world","started_at","last_run","last_published_at","last_latency_seconds"].map(k=>env.SEEN.get(`stats:${k}`)));return{total:+a[0]||0,iran:+a[1]||0,middleEast:+a[2]||0,world:+a[3]||0,startedAt:a[4],lastRun:a[5],lastPublishedAt:a[6],latency:+a[7]||0}}function statsText(s){return [`<b>📊 آمار ربات نبض</b>`,``,`👤 مدیر: @${ADMIN_USERNAME}`,``,`<b>📰 کل اخبار ارسال‌شده:</b> ${s.total}`,``,`🇮🇷 ایران: ${s.iran}`,`🌍 خاورمیانه: ${s.middleEast}`,`🌎 جهان: ${s.world}`,``,`<b>⏱ آخرین تأخیر:</b> ${s.latency?s.latency+" ثانیه":"هنوز خبری ارسال نشده"}`,``,s.startedAt?`🟢 شروع ثبت آمار: ${fmt(s.startedAt)}`:"🟢 شروع ثبت آمار: نامشخص",s.lastPublishedAt?`📰 آخرین انتشار: ${fmt(s.lastPublishedAt)}`:"📰 آخرین انتشار: هنوز انجام نشده",s.lastRun?`⚙️ آخرین اجرای ربات: ${fmt(s.lastRun)}`:"⚙️ آخرین اجرای ربات: نامشخص"].join("\n")}
async function tg(token,method,payload){const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});return await r.json()}function norm(v){const s=String(v||"").trim();return/^\d+$/.test(s)?`-100${s}`:s}function eh(v){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}function ea(v){return eh(v).replace(/'/g,"&#39;")}function fmt(v){const d=new Date(v);return isNaN(d)?"نامشخص":d.toISOString().replace("T"," ").replace(/\.\d{3}Z$/," UTC")}function safe(v){return String(v||"").toLowerCase().replace(/[^a-z0-9_-]+/g,"_").slice(0,100)}async function sha(v){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,"0")).join("")}
